-- SECURITY NOTE:
-- This migration used to include a hardcoded credential update.
-- Credentials must never be committed to source control.
-- Use Supabase Admin API/CLI with secret management outside this repository.
